name = "Hardworking Bees"
author = "TM4"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f60fbf01ecf07fb95a6239953fa78a1da3433ded54a397e5b50cdeb8f7bba896"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
