name: Build modpack
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Packwiz packing
        run: |
          chmod +x ./packwiz
          ./packwiz cf export --output HardworkingBeesCF.zip
      - uses: actions/upload-artifact@v4
        with:
          name: Hardworking Bees Modpack CF
          path: HardworkingBeesCF.zip
